---
abstract: 'Mojolicious + http://fortawesome.github.io/Font-Awesome/'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-FontAwesome4
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 5.00
  Mojolicious::Plugin::AssetPack: 0.22
resources:
  bugtracker: https://github.com/jhthorsen/mojolicious-plugin-fontawesome4/issues
  homepage: https://github.com/jhthorsen/mojolicious-plugin-fontawesome4
  repository: https://github.com/jhthorsen/mojolicious-plugin-fontawesome4.git
version: 4.2000
